ZSH_DISABLE_COMPFIX="true"
DISABLE_AUTO_TITLE="true"

export ZSH=~/.oh-my-zsh

# simple single line
# ZSH_THEME="muse"
# multi line
ZSH_THEME="fino"

ZSH_CUSTOM=~/dotfiles/oh-my-zsh-custom

MAGIC_ENTER_GIT_COMMAND='git status -u .'
MAGIC_ENTER_OTHER_COMMAND='ls -GFlahp .'

plugins=(git ap-common magic-enter jsontools)

source $ZSH/oh-my-zsh.sh

unset LSCOLORS
export CLICOLOR=1
export CLICOLOR_FORCE=1
# solarized
# export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD