export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
white=$(tput setaf 7)
blue=$(tput setaf 4)
bold=$(tput bold)
reset=$(tput sgr0)
PS1='\[$white$bold\]\h\[$reset\]:\[$blue$bold\]\w\[$reset\]\$ '

source ~/dotfiles/git/git-completion.bash
source /usr/local/etc/bash_completion.d/hub.bash_completion.sh
source `brew --prefix`/Library/Contributions/brew_bash_completion.sh

alias gco='git co'
alias gci='git ci'
alias grb='git rb'
alias gs='git s'
alias gl='git --no-pager l -n 10 ; echo'

alias ll="ls -Glahp"
alias lsl="ls -Glahp"

eval "$(hub alias -s)"

function tabname {
  printf "\e]1;$1\a"
}
 
function winname {
  printf "\e]2;$1\a"
}

if [ -f ~/.bashrc_local ]; then
   source ~/.bashrc_local
fi

