export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export PS1="\[$(tput bold)\]\[$(tput setaf 4)\][\u@\h \w]\\$ \[$(tput sgr0)\]"

source ~/dotfiles/git/git-completion.bash
source /usr/local/etc/bash_completion.d/hub.bash_completion.sh
source `brew --prefix`/Library/Contributions/brew_bash_completion.sh

alias gco='git co'
alias gci='git ci'
alias grb='git rb'
alias gs='git s'
alias gl='git l'

alias ll="ls -Glahp"

eval "$(hub alias -s)"

function tabname {
  printf "\e]1;$1\a"
}
 
function winname {
  printf "\e]2;$1\a"
}

